-- 1. GENRE 샘플 데이터
INSERT INTO GENRE (GENRE_NAME) VALUES ('문학');
INSERT INTO GENRE (GENRE_NAME) VALUES ('역사');
INSERT INTO GENRE (GENRE_NAME) VALUES ('과학');
INSERT INTO GENRE (GENRE_NAME) VALUES ('자기계발');
INSERT INTO GENRE (GENRE_NAME) VALUES ('기술');

-- 2. USERS 샘플 데이터
INSERT INTO USERS (NAME, AGE, JOIN_DATE) VALUES ('김민준', 28, SYSTIMESTAMP);
INSERT INTO USERS (NAME, AGE, JOIN_DATE) VALUES ('이서연', 34, SYSTIMESTAMP);
INSERT INTO USERS (NAME, AGE, JOIN_DATE) VALUES ('박진서', 22, SYSTIMESTAMP);
INSERT INTO USERS (NAME, AGE, JOIN_DATE) VALUES ('최수아', 41, SYSTIMESTAMP);
INSERT INTO USERS (NAME, AGE, JOIN_DATE) VALUES ('정도윤', 19, SYSTIMESTAMP);

-- 3. BOOK 샘플 데이터 (GENRE_CODE는 INSERT 순서 기준 1~5)
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('채식주의자',       '한강',       1, '9788936434595');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('82년생 김지영',    '조남주',     1, '9788954651288');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('총균쇠',           '재레드 다이아몬드', 2, '9788950928001');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('사피엔스',         '유발 하라리', 2, '9788934972464');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('코스모스',         '칼 세이건',  3, '9788983711892');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('이기적 유전자',    '리처드 도킨스', 3, '9788932473901');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('아주 작은 습관',   '제임스 클리어', 4, '9788991013·4'); -- ISBN 임의값
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('미라클 모닝',      '할 엘로드',  4, '9788996991282');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('클린 코드',        '로버트 마틴', 5, '9788966260959');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('자바의 정석',      '남궁성',     5, '9788994492032');

-- 4. BOOK_ITEM 샘플 데이터
-- 채식주의자 2권 (BOOK_ID=1)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (1, '대여가능');
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (1, '대여가능');

-- 82년생 김지영 1권 (BOOK_ID=2)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (2, '대여가능');

-- 총균쇠 2권 (BOOK_ID=3)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (3, '대여가능');
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (3, '대여가능');

-- 사피엔스 1권 (BOOK_ID=4)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (4, '대여가능');

-- 코스모스 2권 (BOOK_ID=5)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (5, '대여가능');
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (5, '대여가능');

-- 이기적 유전자 1권 (BOOK_ID=6)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (6, '대여가능');

-- 아주 작은 습관 1권 (BOOK_ID=7)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (7, '대여가능');

-- 미라클 모닝 2권 (BOOK_ID=8)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (8, '대여가능');
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (8, '대여중');

-- 클린 코드 1권 (BOOK_ID=9)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (9, '대여가능');

-- 자바의 정석 2권 (BOOK_ID=10)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (10, '대여가능');
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (10, '대여가능');

COMMIT;