SELECT *
	FROM RENT r ;

SELECT *
	FROM BOOK_ITEM bi;

SELECT *
	FROM BOOK_ITEM bi 
	WHERE bi.STATUS = '대여가능';

SELECT r.RENT_ID, b.TITLE, r.RENT_DATE, r.RETURN_DATE
			FROM RENT r
			JOIN BOOK_ITEM bi ON r.ITEM_ID = bi.ITEM_ID
			JOIN BOOK b ON bi.BOOK_ID = b.BOOK_ID
			WHERE r.USER_ID = 1;
			
			