-- 1. GENRE 샘플 데이터
INSERT INTO GENRE (GENRE_NAME) VALUES ('문학');
INSERT INTO GENRE (GENRE_NAME) VALUES ('역사');
INSERT INTO GENRE (GENRE_NAME) VALUES ('과학');
INSERT INTO GENRE (GENRE_NAME) VALUES ('자기계발');
INSERT INTO GENRE (GENRE_NAME) VALUES ('기술');

-- 2. USERS 샘플 데이터
INSERT INTO USERS (NAME, AGE, PASSWORD, JOIN_DATE) VALUES ('김민준', 28, '1234', SYSTIMESTAMP);
INSERT INTO USERS (NAME, AGE, PASSWORD, JOIN_DATE) VALUES ('이서연', 34, '1234', SYSTIMESTAMP);
INSERT INTO USERS (NAME, AGE, PASSWORD, JOIN_DATE) VALUES ('박진서', 22, '1234', SYSTIMESTAMP);
INSERT INTO USERS (NAME, AGE, PASSWORD, JOIN_DATE) VALUES ('최수아', 41, '1234', SYSTIMESTAMP);
INSERT INTO USERS (NAME, AGE, PASSWORD, JOIN_DATE) VALUES ('정도윤', 19, '1234', SYSTIMESTAMP);

-- 3. BOOK 샘플 데이터 (GENRE_CODE는 INSERT 순서 기준 1~5)
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('채식주의자',       '한강',       1, '9788936434595');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('82년생 김지영',    '조남주',     1, '9788954651288');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('총균쇠',           '재레드 다이아몬드', 2, '9788950928001');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('사피엔스',         '유발 하라리', 2, '9788934972464');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('코스모스',         '칼 세이건',  3, '9788983711892');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('이기적 유전자',    '리처드 도킨스', 3, '9788932473901');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('아주 작은 습관',   '제임스 클리어', 4, '9788991013·4'); -- ISBN 임의값
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('미라클 모닝',      '할 엘로드',  4, '9788996991282');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('클린 코드',        '로버트 마틴', 5, '9788966260959');
INSERT INTO BOOK (TITLE, AUTHOR, GENRE_CODE, ISBN) VALUES ('자바의 정석',      '남궁성',     5, '9788994492032');

-- 4. BOOK_ITEM 샘플 데이터
-- 채식주의자 2권 (BOOK_ID=1)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (1, '대여가능');
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (1, '대여가능');

-- 82년생 김지영 1권 (BOOK_ID=2)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (2, '대여가능');

-- 총균쇠 2권 (BOOK_ID=3)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (3, '대여가능');
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (3, '대여가능');

-- 사피엔스 1권 (BOOK_ID=4)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (4, '대여가능');

-- 코스모스 2권 (BOOK_ID=5)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (5, '대여가능');
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (5, '대여가능');

-- 이기적 유전자 1권 (BOOK_ID=6)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (6, '대여가능');

-- 아주 작은 습관 1권 (BOOK_ID=7)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (7, '대여가능');

-- 미라클 모닝 2권 (BOOK_ID=8)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (8, '대여가능');
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (8, '대여중');

-- 클린 코드 1권 (BOOK_ID=9)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (9, '대여가능');

-- 자바의 정석 2권 (BOOK_ID=10)
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (10, '대여가능');
INSERT INTO BOOK_ITEM (BOOK_ID, STATUS) VALUES (10, '대여가능');

-- 5. RENT 샘플 데이터
-- BOOK_ITEM ITEM_ID 참고:
-- 1~2: 채식주의자, 3: 82년생 김지영, 4~5: 총균쇠, 6: 사피엔스
-- 7~8: 코스모스, 9: 이기적 유전자, 10: 아주 작은 습관
-- 11~12: 미라클 모닝(12번 대여중), 13: 클린 코드, 14~15: 자바의 정석

-- 반납 완료 대여 이력
INSERT INTO RENT (USER_ID, ITEM_ID, RENT_DATE, DUE_DATE, RETURN_DATE)
    VALUES (1, 1,  SYSDATE-30, SYSDATE-23, SYSDATE-25); -- 김민준 - 채식주의자 (정상 반납)

INSERT INTO RENT (USER_ID, ITEM_ID, RENT_DATE, DUE_DATE, RETURN_DATE)
    VALUES (2, 3,  SYSDATE-20, SYSDATE-13, SYSDATE-14); -- 이서연 - 82년생 김지영 (정상 반납)

INSERT INTO RENT (USER_ID, ITEM_ID, RENT_DATE, DUE_DATE, RETURN_DATE)
    VALUES (3, 6,  SYSDATE-15, SYSDATE-8,  SYSDATE-10); -- 박진서 - 사피엔스 (정상 반납)

INSERT INTO RENT (USER_ID, ITEM_ID, RENT_DATE, DUE_DATE, RETURN_DATE)
    VALUES (4, 9,  SYSDATE-25, SYSDATE-18, SYSDATE-16); -- 최수아 - 이기적 유전자 (연체 후 반납)

INSERT INTO RENT (USER_ID, ITEM_ID, RENT_DATE, DUE_DATE, RETURN_DATE)
    VALUES (5, 13, SYSDATE-40, SYSDATE-33, SYSDATE-33); -- 정도윤 - 클린 코드 (당일 반납)

INSERT INTO RENT (USER_ID, ITEM_ID, RENT_DATE, DUE_DATE, RETURN_DATE)
    VALUES (1, 4,  SYSDATE-50, SYSDATE-43, SYSDATE-45); -- 김민준 - 총균쇠 (정상 반납)

INSERT INTO RENT (USER_ID, ITEM_ID, RENT_DATE, DUE_DATE, RETURN_DATE)
    VALUES (2, 7,  SYSDATE-10, SYSDATE-3,  SYSDATE-4);  -- 이서연 - 코스모스 (정상 반납)

-- 대여중 (RETURN_DATE NULL)
INSERT INTO RENT (USER_ID, ITEM_ID, RENT_DATE, DUE_DATE, RETURN_DATE)
    VALUES (3, 12, SYSDATE-5,  SYSDATE+2,  NULL);        -- 박진서 - 미라클 모닝 (대여중, 반납기한 미도래)

-- 연체 중 (DUE_DATE < SYSDATE, RETURN_DATE NULL)
INSERT INTO RENT (USER_ID, ITEM_ID, RENT_DATE, DUE_DATE, RETURN_DATE)
    VALUES (5, 10, SYSDATE-14, SYSDATE-7,  NULL);        -- 정도윤 - 아주 작은 습관 (연체 중)

COMMIT;