-- 1. GENRE 테이블
CREATE TABLE GENRE (
    GENRE_CODE  NUMBER          GENERATED ALWAYS AS IDENTITY,
    GENRE_NAME  VARCHAR2(100)   NOT NULL,
    CONSTRAINT PK_GENRE PRIMARY KEY (GENRE_CODE)
);

-- 2. USERS 테이블
CREATE TABLE USERS (
    USER_ID     NUMBER          GENERATED ALWAYS AS IDENTITY,
    NAME        VARCHAR2(100)   NOT NULL,
    AGE         NUMBER(3),
    JOIN_DATE   TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);

-- 3. BOOK 테이블
CREATE TABLE BOOK (
    BOOK_ID     NUMBER          GENERATED ALWAYS AS IDENTITY,
    TITLE       VARCHAR2(500)   NOT NULL,
    AUTHOR      VARCHAR2(200),
    GENRE_CODE  NUMBER,
    ISBN        VARCHAR2(13),
    CONSTRAINT PK_BOOK       PRIMARY KEY (BOOK_ID),
    CONSTRAINT UQ_BOOK_ISBN  UNIQUE (ISBN),
    CONSTRAINT FK_BOOK_GENRE FOREIGN KEY (GENRE_CODE)
        REFERENCES GENRE (GENRE_CODE)
);

-- 4. BOOK_ITEM 테이블
CREATE TABLE BOOK_ITEM (
    ITEM_ID     NUMBER          GENERATED ALWAYS AS IDENTITY,
    BOOK_ID     NUMBER          NOT NULL,
    STATUS      VARCHAR2(20)    DEFAULT '대여가능' NOT NULL,
    CONSTRAINT PK_BOOK_ITEM PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_ITEM_BOOK FOREIGN KEY (BOOK_ID)
        REFERENCES BOOK (BOOK_ID)
);

-- 5. RENT 테이블
CREATE TABLE RENT (
    RENT_ID     NUMBER          GENERATED ALWAYS AS IDENTITY,
    USER_ID     NUMBER          NOT NULL,
    ITEM_ID     NUMBER          NOT NULL,
    RENT_DATE   DATE            DEFAULT SYSDATE NOT NULL,
    DUE_DATE    DATE            NOT NULL,
    RETURN_DATE DATE,
    CONSTRAINT PK_RENT      PRIMARY KEY (RENT_ID),
    CONSTRAINT FK_RENT_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID),
    CONSTRAINT FK_RENT_ITEM FOREIGN KEY (ITEM_ID)
        REFERENCES BOOK_ITEM (ITEM_ID)
);

-- 6. RESERVATION 테이블
CREATE TABLE RESERVATION (
    RESERVATION_ID   NUMBER     GENERATED ALWAYS AS IDENTITY,
    USER_ID          NUMBER     NOT NULL,
    BOOK_ID          NUMBER     NOT NULL,
    RESERVATION_DATE DATE       DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RESERVATION PRIMARY KEY (RESERVATION_ID),
    CONSTRAINT FK_RESERV_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID),
    CONSTRAINT FK_RESERV_BOOK FOREIGN KEY (BOOK_ID)
        REFERENCES BOOK (BOOK_ID)
);