SELECT *
	FROM RENT r ;

SELECT *
	FROM BOOK_ITEM bi;

SELECT *
	FROM BOOK_ITEM bi 
	WHERE bi.STATUS = '대여가능';

SELECT r.RENT_ID, b.TITLE, r.RENT_DATE, r.RETURN_DATE
			FROM RENT r
			JOIN BOOK_ITEM bi ON r.ITEM_ID = bi.ITEM_ID
			JOIN BOOK b ON bi.BOOK_ID = b.BOOK_ID
			WHERE r.USER_ID = 1;
			

SELECT bi.ITEM_ID
	    FROM BOOK_ITEM bi
	    JOIN BOOK b ON bi.BOOK_ID = b.BOOK_ID
	    LEFT JOIN RENT r ON bi.ITEM_ID = r.ITEM_ID
	    WHERE b.TITLE = '미라클 모닝'
	      AND bi.STATUS = '대여가능'
	    GROUP BY bi.ITEM_ID
	    ORDER BY COUNT(r.RENT_ID) ASC, bi.ITEM_ID ASC
	    FETCH FIRST 1 ROW ONLY;


UPDATE BOOK_ITEM
		SET STATUS = '대여중'
		WHERE ITEM_ID = 1;
