spring.config.import=optional:file:.env[.properties]

# DataSource
spring.datasource.driver-class-name=${DB_DRIVER}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME:EDU}
spring.datasource.password=${DB_PASSWORD}

# MyBatis Config
mybatis.config-location=classpath:mybatis_config.xml

# JWT Sercret key
jwt.secret=${JWT_SECRET}